basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: Simon
    url: https://dongxiaoming.com
  description: This is a sample server celler server.
  license:
    name: MIT
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Mongosteen API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: 测试 API 是否可以正常工作
      parameters:
      - description: Account ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: 测试 API 是否可以正常工作
      tags:
      - Ping
securityDefinitions:
  BasicAuth(JWT):
    type: basic
swagger: "2.0"
